apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-composition
spec:
  compositeTypeRef:
    apiVersion: custom-api.example.org/v1alpha1
    kind: xBucket
  resources:
    - base:
        apiVersion: storage.gcp.upbound.io/v1beta1
        kind: Bucket
        name: bucket
        spec:
          # forProvider:
          #   location: US
          providerConfigRef:
            name: default
      patches:
      - type: FromCompositeFieldPath
        fromFieldPath: "spec.location"
        toFieldPath: "spec.forProvider.location"
      readinessChecks:
        - matchCondition:
            status: 'True'
            type: Ready
          type: MatchCondition
