apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/morey-tech/argocd-crossplane'
    path: applications/my-app
    targetRevision: HEAD
  destination:
    namespace: my-app
    name: kind-argocd-crossplane
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
