apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/morey-tech/argocd-crossplane
        revision: HEAD
        directories:
          - path: applications/
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      source:
        repoURL: https://github.com/morey-tech/argocd-crossplane
        targetRevision: HEAD
        path: '{{.path.path}}'
        kustomize: {}
      destination:
        name: kind-argocd-crossplane
        namespace: '{{.path.basenameNormalized}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - FailOnSharedResource=true
      info:
        - name: 'Application Name: '
          value: '{{.path.basenameNormalized}}'
