apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: akuity-platform/argocd-crossplane/appsets/
    repoURL: 'https://github.com/morey-tech/argocd-crossplane'
    targetRevision: HEAD
    directory: {}
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
